System information (for reproducibility):

In [1]:
versioninfo()

Julia Version 1.9.0
Commit 8e63055292 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × AMD Ryzen 7 5800 8-Core Processor              
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 9 on 16 virtual cores
Environment:
  JULIA_NUM_THREADS = 8


Load packages:

In [2]:
using Pkg

Pkg.activate(pwd())
Pkg.instantiate()
Pkg.status()

using DataFrames, Convex, MosekTools, MathOptInterface, LinearAlgebra, JuMP, Pajarito, Gurobi

  Activating project at `C:\Users\larry\Dropbox\zza\UCLA\academic\year 3\quarter 3\257\biostat-257-2023-spring\hw5`


Status `C:\Users\larry\Dropbox\zza\UCLA\academic\year 3\quarter 3\257\biostat-257-2023-spring\hw5\Project.toml`
  [f65535da] Convex v0.15.3
  [a93c6f00] DataFrames v1.5.0
  [87dc4568] HiGHS v1.5.1
  [b99e6be6] Hypatia v0.7.3
  [4076af6c] JuMP v1.11.1
  [b8f27783] MathOptInterface v1.16.0
  [6405355b] Mosek v10.0.2
  [1ec41992] MosekTools v0.15.0
  [2f354839] Pajarito v0.8.2
  [08abe8d2] PrettyTables v2.2.4
  [c946c3f1] SCS v1.1.4
  [3eaba693] StatsModels v0.7.2


In this exercise, we practice using disciplined convex programming (SDP in particular) to solve optimal design problems.

## Introduction to Optimal design

Consider a linear model
\begin{eqnarray*}
	y_i = \mathbf{x}_i^T \boldsymbol{\beta} + \epsilon_i, \quad i = 1,\ldots, n,
\end{eqnarray*}
where $\epsilon_i$ are independent Gaussian noises with common variance $\sigma^2$. It is well known that the least squares estimate $\hat{\boldsymbol{\beta}}$ is unbiased and has covariance $\sigma^2 (\sum_{i=1}^n \mathbf{x}_i \mathbf{x}_i^T)^{-1}$. 

In **exact optimal design**, given total number of $n$ allowable experiments, we want to choose among a list of $m$ candidate design points $\{\mathbf{x}_1, \ldots, \mathbf{x}_m\}$ such that the covariance matrix is minimized in some sense. In mathematical terms, we want to find an integer vector $\mathbf{n} = (n_1, \ldots, n_m)$ such that $n_i \ge 0$, $\sum_{i=1}^m n_i = n$, and the matrix $\mathbf{V} = \left( \sum_{i=1}^m n_i \mathbf{x}_i \mathbf{x}_i^T \right)^{-1}$ is "small".

In **approximate optimal design**,  we want to find a probability vector $\mathbf{p} = (p_1, \ldots, p_m)$ such that $p_i \ge 0$, $\sum_{i=1}^m p_i = 1$, and the matrix $\mathbf{V} = \left( \sum_{i=1}^m p_i \mathbf{x}_i \mathbf{x}_i^T \right)^{-1}$ is "small".

Commonly used optimal design criteria include:

- In **$D$-optimal design**, we minimize the determinant of $\mathbf{V}$
\begin{eqnarray*}
	&\text{minimize}& \det \left( \sum_{i=1}^m p_i \mathbf{x}_i \mathbf{x}_i^T \right)^{-1} \\
	&\text{subject to}& p_i \ge 0, \sum_{i=1}^m p_i = 1.
\end{eqnarray*}

- In **$E$-optimal design**, we minimize the spectral norm, i.e., the maximum eigenvalue of $\mathbf{V}$
\begin{eqnarray*}
	&\text{minimize}& \lambda_{\text{max}} \left( \sum_{i=1}^m p_i \mathbf{x}_i \mathbf{x}_i^T \right)^{-1} \\
	&\text{subject to}& p_i \ge 0, \sum_{i=1}^m p_i = 1.	
\end{eqnarray*}
Statistically we are minimizing the maximum variance of $\sum_{j=1}^p a_j \text{var}(\hat \beta_j)$ over all vectors $\mathbf{a}$ with unit norm.

- In **$A$-optimal design**, we minimize the trace of $\mathbf{V}$
\begin{eqnarray*}
	&\text{minimize}& \text{tr} \left( \sum_{i=1}^m p_i \mathbf{x}_i \mathbf{x}_i^T \right)^{-1} \\
	&\text{subject to}& p_i \ge 0, \sum_{i=1}^m p_i = 1.
\end{eqnarray*}
Statistically we are minimizing the total variance $\sum_{j=1}^p \text{var}(\hat \beta_j)$.

## Q1 (10 pts) 3x4 factorial design

A drug company ask you to help design a two factor clinical trial, in which treatment A has three levels (A1, A2, and A3) and treatment B has four levels (B1, B2, B3, and B4). Drug company also tells you that the treatment combination A3:B4 has undesirable side effects so we ignore this design point. 

Using dummy coding with A1 and B1 as the baseline levels, find the matrix $C$ with each row a unique design point.

**Sol.**

In [3]:
treatment_combination = ["A1:B1", "A2:B1", "A3:B1", "A1:B2", "A2:B2", 
                         "A3:B2", "A1:B3", "A2:B3", "A3:B3", "A1:B4", "A2:B4"]
A2 = [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1]
A3 = [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
B2 = [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
B3 = [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0]
B4 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]

df = DataFrame(treatment_combination = treatment_combination, intcept = ones(11),
               A2 = A2, A3 = A3, B2 = B2, B3 = B3, B4 = B4)
df


11×7 DataFrame
 Row │ treatment_combination  intcept  A2     A3     B2     B3     B4    
     │ String                 Float64  Int64  Int64  Int64  Int64  Int64 
─────┼───────────────────────────────────────────────────────────────────
   1 │ A1:B1                      1.0      0      0      0      0      0
   2 │ A2:B1                      1.0      1      0      0      0      0
   3 │ A3:B1                      1.0      0      1      0      0      0
   4 │ A1:B2                      1.0      0      0      1      0      0
   5 │ A2:B2                      1.0      1      0      1      0      0
   6 │ A3:B2                      1.0      0      1      1      0      0
   7 │ A1:B3                      1.0      0      0      0      1      0
   8 │ A2:B3                      1.0      1      0      0      1      0
   9 │ A3:B3                      1.0      0      1      0      1      0
  10 │ A1:B4                      1.0      0      0      0      0      1
  11 │ A2:B4                      1.0      1      0      0      0      1

## Q2 (30 pts) Find approximate optimal designs

Using semidefinite programming (SDP) software to find the approximate D-, E-, and A-optimal designs for this clinical trial.

Hint: This is what I got, which may or may not be correct.

```
Approximate Optimal Design
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ design_pt │   D_opt │   E_opt │   A_opt │ D_opt_n │ E_opt_n │ A_opt_n │
│    String │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │ Float64 │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│      A1B1 │   0.082 │   0.272 │   0.200 │       8 │      27 │      20 │
│      A2B1 │   0.082 │   0.152 │   0.101 │       8 │      15 │      10 │
│      A3B1 │   0.097 │   0.114 │   0.104 │      10 │      11 │      10 │
│      A1B2 │   0.082 │   0.057 │   0.086 │       8 │       6 │       9 │
│      A2B2 │   0.082 │   0.039 │   0.051 │       8 │       4 │       5 │
│      A3B2 │   0.097 │   0.057 │   0.068 │      10 │       6 │       7 │
│      A1B3 │   0.082 │   0.057 │   0.086 │       8 │       6 │       9 │
│      A2B3 │   0.082 │   0.039 │   0.051 │       8 │       4 │       5 │
│      A3B3 │   0.097 │   0.057 │   0.068 │      10 │       6 │       7 │
│      A1B4 │   0.109 │   0.081 │   0.106 │      11 │       8 │      11 │
│      A2B4 │   0.109 │   0.073 │   0.080 │      11 │       7 │       8 │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
```

**Sol.**

In [4]:
X = hcat(ones(11), A2, A3, B2, B3, B4)
# define problem
P = Variable(size(X, 1))
# D opt
D_problem = minimize(-logdet(quadform(X, diagm(P)))) # objective
D_problem.constraints += sum(P) == 1; # constraint
D_problem.constraints += P >= 0; # constraint
# define solver
const MOI = MathOptInterface
solver = Mosek.Optimizer()
MOI.set(solver, MOI.RawOptimizerAttribute("LOG"), 0)
solve!(D_problem, solver)
# Check the status, optimal value, and minimizer of the problem
D_problem.status, D_problem.optval, P.value

(MathOptInterface.OPTIMAL, 8.98683156359766, [0.08194043080515269; 0.08195446134009557; … ; 0.10891345308189594; 0.1089056858612344;;])

In [5]:
# save number
D_opt_n = vec(round.(P.value .* 100))

11-element Vector{Float64}:
  8.0
  8.0
 10.0
  8.0
  8.0
 10.0
  8.0
  8.0
 10.0
 11.0
 11.0

In [6]:
# E opt
E_problem = minimize(-eigmin(quadform(X, diagm(P)))) # objective
E_problem.constraints += sum(P) == 1; # constraint
E_problem.constraints += P >= 0; # constraint
# define solver
const MOI = MathOptInterface
solver = Mosek.Optimizer()
MOI.set(solver, MOI.RawOptimizerAttribute("LOG"), 0)
solve!(E_problem, solver)
# Check the status, optimal value, and minimizer of the problem
E_problem.status, E_problem.optval, P.value

(MathOptInterface.OPTIMAL, -0.076923076725408, [0.27116845314152616; 0.15605925265960144; … ; 0.0810948952008921; 0.07274779284884167;;])

In [7]:
# save number
E_opt_n = vec(round.(P.value .* 100))

11-element Vector{Float64}:
 27.0
 16.0
 11.0
  6.0
  4.0
  6.0
  6.0
  4.0
  6.0
  8.0
  7.0

In [8]:
# A opt
Y = Semidefinite(size(X, 2))
A_matrix = [quadform(X, diagm(P)) diagm(ones(size(X, 2))); diagm(ones(size(X, 2))) Y]
A_problem = minimize(tr(Y)) # objective
A_problem.constraints += sum(P) == 1; # constraint
A_problem.constraints += P >= 0; # constraint
A_problem.constraints += A_matrix in :SDP; # constraint
# define solver
const MOI = MathOptInterface
solver = Mosek.Optimizer()
MOI.set(solver, MOI.RawOptimizerAttribute("LOG"), 0)
solve!(A_problem, solver)
# Check the status, optimal value, and minimizer of the problem
A_problem.status, A_problem.optval, P.value

(MathOptInterface.OPTIMAL, 38.92481411739291, [0.19983898379814147; 0.10056827396965753; … ; 0.105562329964215; 0.07988091755458135;;])

In [9]:
# save number
A_opt_n = vec(round.(P.value .* 100))

11-element Vector{Float64}:
 20.0
 10.0
 10.0
  9.0
  5.0
  7.0
  9.0
  5.0
  7.0
 11.0
  8.0

### summary table

In [10]:
df = DataFrame(treatment_combination = treatment_combination, 
               D_opt_n = D_opt_n, E_opt_n = E_opt_n, A_opt_n = A_opt_n)
df

11×4 DataFrame
 Row │ treatment_combination  D_opt_n  E_opt_n  A_opt_n 
     │ String                 Float64  Float64  Float64 
─────┼──────────────────────────────────────────────────
   1 │ A1:B1                      8.0     27.0     20.0
   2 │ A2:B1                      8.0     16.0     10.0
   3 │ A3:B1                     10.0     11.0     10.0
   4 │ A1:B2                      8.0      6.0      9.0
   5 │ A2:B2                      8.0      4.0      5.0
   6 │ A3:B2                     10.0      6.0      7.0
   7 │ A1:B3                      8.0      6.0      9.0
   8 │ A2:B3                      8.0      4.0      5.0
   9 │ A3:B3                     10.0      6.0      7.0
  10 │ A1:B4                     11.0      8.0     11.0
  11 │ A2:B4                     11.0      7.0      8.0

## Q3 (30 pts) Find exact optimal designs

Using mixed-integer semidefinite programming (SDP) software to find the exact D-, E-, and A-optimal designs for this clinical trial.

Hint: This is what I got. Apparently I haven't got the E-optimal design right yet.

```
Exact Optimal Design
┌───────────┬───────┬───────┬───────┐
│ design_pt │ D_opt │ E_opt │ A_opt │
│    String │ Int64 │ Int64 │ Int64 │
├───────────┼───────┼───────┼───────┤
│      A1B1 │     8 │    90 │    20 │
│      A2B1 │     8 │     1 │    10 │
│      A3B1 │    10 │     1 │    10 │
│      A1B2 │     8 │     1 │     9 │
│      A2B2 │     8 │     1 │     5 │
│      A3B2 │    10 │     1 │     7 │
│      A1B3 │     8 │     1 │     9 │
│      A2B3 │     8 │     1 │     5 │
│      A3B3 │    10 │     1 │     7 │
│      A1B4 │    11 │     1 │    10 │
│      A2B4 │    11 │     1 │     8 │
└───────────┴───────┴───────┴───────┘
```

**Sol.**

In [11]:
X = hcat(ones(Int64, 11), A2, A3, B2, B3, B4)
# define problem
N = Variable(size(X, 1), :Int)
# D opt
D_problem = minimize(-logdet(quadform(X, diagm(N)))) # objective
D_problem.constraints += sum(N) == 100; # constraint
D_problem.constraints += N >= 0; # constraint
# define solver
misdp_solver = optimizer_with_attributes(
        Pajarito.Optimizer,
    "oa_solver" => optimizer_with_attributes(
        Gurobi.Optimizer,
        MOI.Silent() => true),
    "conic_solver" => optimizer_with_attributes(
        MosekTools.Optimizer, 
        MOI.Silent() => true),
)
set_attribute(misdp_solver, "time_limit", 60)
MOI.set(misdp_solver, MOI.RawOptimizerAttribute("verbose"), 0)
solve!(D_problem, misdp_solver)
# Check the status, optimal value, and minimizer of the problem
D_problem.status, D_problem.optval, N.value

Set parameter Username
Academic license - for non-commercial use only - expires 2024-05-25


┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396


(MathOptInterface.OPTIMAL, -18.643222034217736, [8.0; 8.0; … ; 11.0; 11.0;;])

In [12]:
A_opt_n = vec(N.value)

11-element Vector{Float64}:
  8.0
  8.0
 10.0
  8.0
  8.0
 10.0
  8.0
  8.0
 10.0
 11.0
 11.0

In [13]:
# E opt
E_problem = minimize(-eigmin(quadform(X, diagm(N)))) # objective
E_problem.constraints += sum(N) == 100; # constraint
E_problem.constraints += N >= 0; # constraint
MOI.set(misdp_solver, MOI.RawOptimizerAttribute("verbose"), 0)
solve!(E_problem, misdp_solver)
# Check the status, optimal value, and minimizer of the problem
E_problem.status, E_problem.optval, N.value

Set parameter Username
Academic license - for non-commercial use only - expires 2024-05-25
new incumbent
new incumbent
new incumbent
new incumbent
new incumbent


(MathOptInterface.OPTIMAL, -7.685749743910843, [34.0; 10.0; … ; 12.0; 3.0;;])

In [14]:
E_opt_n = vec(N.value)

11-element Vector{Float64}:
 34.0
 10.0
 10.0
  8.0
  4.0
  4.0
  6.0
  3.0
  6.0
 12.0
  3.0

In [15]:
# A opt
Y = Semidefinite(size(X, 2))
A_matrix = [quadform(X, diagm(N)) diagm(ones(size(X, 2))); diagm(ones(size(X, 2))) Y]
A_problem = minimize(tr(Y)) # objective
A_problem.constraints += sum(N) == 100; # constraint
A_problem.constraints += N >= 0; # constraint
A_problem.constraints += A_matrix in :SDP; # constraint
MOI.set(misdp_solver, MOI.RawOptimizerAttribute("verbose"), 0)
solve!(A_problem, misdp_solver)
# Check the status, optimal value, and minimizer of the problem
A_problem.status, A_problem.optval, N.value

Set parameter Username
Academic license - for non-commercial use only - expires 2024-05-25
norm of dual is 1.3504917734887614e14

┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396


┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: integer variable solution is not integral to tolerance tol_feas
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:441
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396
┌ Warning: continuous subproblem status SLOW_PROGRESS is not handled
└ @ Pajarito C:\Users\larry\.julia\packages\Pajarito\gSNvz\src\algorithms.jl:396


new incumbent
new incumbent
new incumbent
new incumbent
new incumbent
new incumbent
new incumbent


(MathOptInterface.OPTIMAL, 0.38949673086596137, [20.0; 10.0; … ; 11.0; 8.0;;])

In [16]:
A_opt_n = vec(N.value)

11-element Vector{Float64}:
 20.0
 10.0
 10.0
  9.0
  5.0
  7.0
  8.0
  5.0
  7.0
 11.0
  8.0

### summary table

In [17]:
df = DataFrame(treatment_combination = treatment_combination, 
               D_opt_n = D_opt_n, E_opt_n = E_opt_n, A_opt_n = A_opt_n)
df

11×4 DataFrame
 Row │ treatment_combination  D_opt_n  E_opt_n  A_opt_n 
     │ String                 Float64  Float64  Float64 
─────┼──────────────────────────────────────────────────
   1 │ A1:B1                      8.0     34.0     20.0
   2 │ A2:B1                      8.0     10.0     10.0
   3 │ A3:B1                     10.0     10.0     10.0
   4 │ A1:B2                      8.0      8.0      9.0
   5 │ A2:B2                      8.0      4.0      5.0
   6 │ A3:B2                     10.0      4.0      7.0
   7 │ A1:B3                      8.0      6.0      8.0
   8 │ A2:B3                      8.0      3.0      5.0
   9 │ A3:B3                     10.0      6.0      7.0
  10 │ A1:B4                     11.0     12.0     11.0
  11 │ A2:B4                     11.0      3.0      8.0

## Q4 (30 bonus points) Optimal design with nuisance parameters

Suppose the regression coefficients of linear model $\boldsymbol{\beta}$ is partitioned as $\boldsymbol{\beta} = (\boldsymbol{\beta}_0^T, \boldsymbol{\beta}_1^T)^T$, where $\boldsymbol{\beta}_0$ are nuisance parameters and $\boldsymbol{\beta}_1$ are parameters of primary interest. Given an approximate design $\mathbf{p} = (p_1, \ldots, p_m)$, let the information matrix be partitioned accordingly
$$
\mathbf{I}(\mathbf{p}) = \sum_{i=1}^m p_i \mathbf{x}_i \mathbf{x}_i^T =  \begin{pmatrix}
\mathbf{I}_{00} & \mathbf{I}_{01} \\
\mathbf{I}_{10} & \mathbf{I}_{11}
\end{pmatrix}.
$$
Then the information matrix for $\boldsymbol{\beta}_1$ adjusted for nuisance parameter $\boldsymbol{\beta}_0$ is
$$
\mathbf{I}_{1 \mid 0}(\mathbf{p}) = \mathbf{I}_{11} - \mathbf{I}_{10} \mathbf{I}_{00}^{-1} \mathbf{I}_{01}.
$$

Revisiting the 3x4 factorial design problem in Q1, suppose the drug company only cares about the estimation of A treatment effects. Find the approximate D-, E-, and A-optimal designs.

**Sol.**

-----(Sourced from class note)-----

Here we want to show that minimizing $f\left(\mathbf{I}_{1 \mid 0}^{-1}\right)$, where $f$ is monotone according to the Loewner order, is equivalent to the semidefinite program (SDP)
$$
\begin{array}{rl}
\min _{\mathbf{p}, \mathbf{X}} & f(\mathbf{X}) \\
\text { subject to } & \left(\begin{array}{ccc}
\mathbf{I}_{00} & \mathbf{I}_{01} & \mathbf{0} \\
\mathbf{I}_{10} & \mathbf{I}_{11} & \mathbf{I} \\
\mathbf{0} & \mathbf{I} & \mathbf{X}
\end{array}\right) \succeq \mathbf{0} \\
& \mathbf{p} \geq \mathbf{0}, \quad \mathbf{1}^T \mathbf{p}=1 .
\end{array}
$$
Proof: Assuming $\mathbf{I}_{00}>0$, then
$$
\left(\begin{array}{ccc}
\mathbf{I}_{00} & \mathbf{I}_{01} & \mathbf{0} \\
\mathbf{I}_{10} & \mathbf{I}_{11} & \mathbf{I} \\
\mathbf{0} & \mathbf{I} & \mathbf{X}
\end{array}\right) \geq \mathbf{0}
$$

implies
$$
\left(\begin{array}{cc}
\mathbf{I}_{11} & \mathbf{I} \\
\mathbf{I} & \mathbf{X}
\end{array}\right)-\left(\begin{array}{c}
\mathbf{I}_{10} \\
\mathbf{0}
\end{array}\right) \mathbf{I}_{00}^{-1}\left(\begin{array}{ll}
\mathbf{I}_{01} & \mathbf{0}
\end{array}\right)=\left(\begin{array}{cc}
\mathbf{I}_{11}-\mathbf{I}_{10} \mathbf{I}_{00}^{-1} \mathbf{I}_{01} & \mathbf{I} \\
\mathbf{I} & \mathbf{X}
\end{array}\right) \geq 0,
$$
which in turn implies
$$
\mathbf{X} \geq\left(\mathbf{I}_{11}-\mathbf{I}_{10} \mathbf{I}_{00}^{-1} \mathbf{I}_{01}\right)^{-1}
$$
and thus
$$
f(\mathbf{X}) \geq f\left(\left(\mathbf{I}_{11}-\mathbf{I}_{10} \mathbf{I}_{00}^{-1} \mathbf{I}_{01}\right)^{-1}\right) .
$$
-----


In [18]:
# data need
I_need = X[:, 2:3]
I_nuisance = X[:, [1, 4, 5, 6]]
I_updated = hcat(I_nuisance, I_need)
p0 = size(I_nuisance, 2)
p1 = size(I_need, 2)

# define problem
P = Variable(size(X, 1))
Y = Semidefinite(size(I_need, 2))
New_matrix = [quadform(I_updated, diagm(P)) [zeros(p0, p1); diagm(ones(p1))]; 
              [zeros(p1, p0) diagm(ones(p1))] Y]
# define objective A opt
problem = minimize(tr(Y)) 
# define constraint
problem.constraints += sum(P) == 1; 
problem.constraints += P >= 0; 
problem.constraints += New_matrix in :SDP;
# define solver
const MOI = MathOptInterface
solver = Mosek.Optimizer()
MOI.set(solver, MOI.RawOptimizerAttribute("LOG"), 0)
solve!(problem, solver)
# Check the status, optimal value, and minimizer of the problem
problem.status, problem.optval, P.value

(MathOptInterface.OPTIMAL, 11.656853042410077, [0.13970642365018215; 0.09877599910504548; … ; 9.59935146448211e-8; 9.314828833116653e-8;;])

In [19]:
A_opt_n = vec(round.(P.value * 100))

11-element Vector{Float64}:
 14.0
 10.0
 10.0
 14.0
 10.0
 10.0
 14.0
 10.0
 10.0
  0.0
  0.0

In [20]:
# E opt
problem = minimize(eigmax(Y)) # objective
# define constraint
problem.constraints += sum(P) == 1; 
problem.constraints += P >= 0; 
problem.constraints += New_matrix in :SDP;
# define solver
const MOI = MathOptInterface
solver = Mosek.Optimizer()
MOI.set(solver, MOI.RawOptimizerAttribute("LOG"), 0)
solve!(problem, solver)
# Check the status, optimal value, and minimizer of the problem
problem.status, problem.optval, P.value

(MathOptInterface.OPTIMAL, 7.9999996026613935, [0.1432332302565532; 0.057638074748784816; … ; 0.08029084530545687; 0.0802902413540027;;])

In [21]:
E_opt_n = vec(round.(P.value * 100))

11-element Vector{Float64}:
 14.0
  6.0
  9.0
 14.0
  6.0
  8.0
 14.0
  6.0
  8.0
  8.0
  8.0

In [22]:
# try D opt but failed
# add one more matrix
Z = Semidefinite(size(Y, 2))
Z_matrix = [Y diagm(ones(size(Y, 2))); diagm(ones(size(Y, 2))) Z]
problem = minimize(-logdet(Z)) # objective
# define constraint
problem.constraints += sum(P) == 1; 
problem.constraints += P >= 0; 
problem.constraints += New_matrix in :SDP;
problem.constraints += Z_matrix in :SDP;
# define solver
const MOI = MathOptInterface
solver = Mosek.Optimizer()
MOI.set(solver, MOI.RawOptimizerAttribute("LOG"), 0)
solve!(problem, solver)
# Check the status, optimal value, and minimizer of the problem
problem.status, problem.optval, P.value

┌ Warning: Problem status SLOW_PROGRESS; solution may be inaccurate.
└ @ Convex C:\Users\larry\.julia\packages\Convex\tSTAW\src\solution.jl:342


(MathOptInterface.SLOW_PROGRESS, -34.363284771960416, [0.08875584966389734; 0.08875819778046241; … ; 0.09603215749181727; 0.09603249400689329;;])

In [23]:
D_opt_n = vec(round.(P.value * 100))

11-element Vector{Float64}:
  9.0
  9.0
  9.0
  9.0
  9.0
  9.0
  9.0
  9.0
  9.0
 10.0
 10.0

### summary table

In [24]:
df = DataFrame(treatment_combination = treatment_combination, 
               D_opt_n = D_opt_n, E_opt_n = E_opt_n, A_opt_n = A_opt_n)
df

11×4 DataFrame
 Row │ treatment_combination  D_opt_n  E_opt_n  A_opt_n 
     │ String                 Float64  Float64  Float64 
─────┼──────────────────────────────────────────────────
   1 │ A1:B1                      9.0     14.0     14.0
   2 │ A2:B1                      9.0      6.0     10.0
   3 │ A3:B1                      9.0      9.0     10.0
   4 │ A1:B2                      9.0     14.0     14.0
   5 │ A2:B2                      9.0      6.0     10.0
   6 │ A3:B2                      9.0      8.0     10.0
   7 │ A1:B3                      9.0     14.0     14.0
   8 │ A2:B3                      9.0      6.0     10.0
   9 │ A3:B3                      9.0      8.0     10.0
  10 │ A1:B4                     10.0      8.0      0.0
  11 │ A2:B4                     10.0      8.0      0.0